/**
 * Ported verbatim from vendor/paperspace packages/agent-runtime/src/tools.ts.
 */
import type { PaperContext, PaperTool, ToolDefinition } from './types';
export const SEARCH_MAX_QUERY = 500; export const SEARCH_MAX_RESULTS = 8; export const SEARCH_MAX_PASSAGE = 1200; export const SECTION_MAX_HEADING = 200; export const SECTION_MAX_CHARS = 12000;
const searchDefinition: ToolDefinition = {name:'search_paper', description:'Search passages in the current paper only.', parameters:{type:'object',properties:{query:{type:'string',maxLength:SEARCH_MAX_QUERY}},required:['query'],additionalProperties:false}};
const sectionDefinition: ToolDefinition = {name:'read_section', description:'Read a heading section from the current paper only.', parameters:{type:'object',properties:{heading:{type:'string',maxLength:SECTION_MAX_HEADING}},required:['heading'],additionalProperties:false}};
function stringArg(args: unknown, key: string, max: number): string { if (!args || typeof args !== 'object' || Array.isArray(args) || Object.keys(args).length !== 1 || typeof (args as Record<string, unknown>)[key] !== 'string') throw new Error(`invalid ${key}`); const value=(args as Record<string, string>)[key].trim(); if (!value || value.length > max) throw new Error(`invalid ${key}`); return value; }
export function createPaperTools(paper: PaperContext): PaperTool[] {
  return [{definition:searchDefinition, execute: async args => { const query=stringArg(args,'query',SEARCH_MAX_QUERY); const terms=query.toLowerCase().split(/\s+/); const paragraphs=paper.markdown.split(/\n\s*\n/); return paragraphs.map((text,index)=>({text,index,score:terms.filter(t=>text.toLowerCase().includes(t)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,SEARCH_MAX_RESULTS).map(({text,index})=>({passage:text.slice(0,SEARCH_MAX_PASSAGE),index})); }},{definition:sectionDefinition, execute: async args => { const heading=stringArg(args,'heading',SECTION_MAX_HEADING); const lines=paper.markdown.split('\n'); const wanted=heading.toLowerCase(); const start=lines.findIndex(line=>/^#{1,6}\s+/.test(line) && line.replace(/^#{1,6}\s+/,'').trim().toLowerCase()===wanted); if(start<0) return {heading,content:null}; const level=(lines[start].match(/^#+/)??[''])[0].length; const end=lines.findIndex((line,i)=>i>start && new RegExp(`^#{1,${level}}\\s+`).test(line)); return {heading:lines[start].replace(/^#+\s+/,''),content:lines.slice(start,end<0?undefined:end).join('\n').slice(0,SECTION_MAX_CHARS)}; }}];
}
